# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ip',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='session_key',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ip',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='history_type',
            field=models.IntegerField(choices=[(1, 'Комментарий создан'), (2, 'Комментарий сохранен'), (3, 'Комментарий оценен'), (4, 'Материал создан'), (5, 'Материал сохранен'), (6, 'Материал оценен'), (7, 'Жалоба на комментарий'), (8, 'Пользовательский материал оценен'), (9, 'Жалоба на пользовательский материал')], db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
    ]
